const express = require("express");
const app = express();
const bodyParser = require("body-parser");

/*
 * Express only excepts dynamic HTML file so you must inject a
 * static middleware function to use a static HTML file with express
 */
app.use(express.static(__dirname + "/public_html"));

// The default packet is urlencoded so this must be included
app.use(bodyParser.urlencoded({ extended: false }));

// However to send to MailChimp you must use a json package so this is also necessary
app.use(bodyParser.json());

app.listen(3000, function () {
  console.log("Listening on: 3000");
});

// Whenever the site receives a request at the root of the site
app.post("/", function (req, res) {
  addEmailToMailChimp(req.body.email);
  res.end("success");
});

function addEmailToMailChimp(email) {
  // generated by postman
  var request = require("request");
  var options = {
    method: "POST",
    url: "https://us18.api.mailchimp.com/3.0/lists/e56325e722/members",
    headers: {
      Authorization:
        "Basic YW55c3RyaW5nOmZiZTFjMjczMDU2NmFhYjE5MTcyNGMyMjkwZDVlMjc2LXVzMTg=",
      "Content-Type": "application/json",
      Cookie:
        "ak_bmsc=32BFE5945E20A77CFC7B84CA939CB0A9~000000000000000000000000000000~YAAQDqtZaJh8m+eAAQAA7PzH8g8VkDF73/jgOAs00VT1pzJP8jCDhmQT+lxlfuqrPEidy5qvmNyi6ALOJ4LQBlrLTSptHAUh99z/eVh42miTyIqLjgaHWOKPlTtQ+V8XTIWtkPnDLbhZfDgjdNFyjjEQW5WD7dY0mVq/+5Zlx3wUs237eOC12J3mUEOpf/jLxwvMHh6QwjawQw3kZKTkKOZ9QhBicYnOYVytxg+hyBvRUBXy44EOSmRhmmk4nRO62zESKD8Svdg9HwyfFk8dcsAWXyhHLkMP+RH0k4bqFo2GuGeI0b3MePMS7DwRd7k1WNZLu8mt4ow0PKEbLAXAApHQGPe8HXoulNwr7YfIWSjP+lA0Ak3AtnoyalDlaxX3y0c=; bm_sv=24BDABBDA6EB26B79BDEEA2CD25F5C13~YAAQDqtZaLvZm+eAAQAA3p7T8g9G2he5z3DQGaLJPVa051KBjrmFt549cY8MLsZeTOvPyz+Y1H1jNMCP9F+9H5hi/je/DtK1I6ab9Kgucu/xhZCYN28/t9RKiuDFKXPbI0UbEd2BxI9f6YClggWUaqBrVkkwgBaWY4oh5ILb9h8SdV3kSFA1hmkuzbAYRfDZftDXnmYtGuZv2DVzHtL8sh9OxunEPcSgZFXdcwk162UEy7T0TyYQ17woV4fwID9KbPV5JW7G/Q==~1",
    },
    body: JSON.stringify({
      email_address: email,
      status: "subscribed",
    }),
  };
  request(options, function (error, response) {
    if (error) throw new Error(error);
    console.log(response.body);
  });
}
